; PlatformIO Project Configuration File
;
; ESP32 dev board, framework Arduino
; Порт определяется автоматически. Чтобы посмотреть список портов:
;   pio device list
; При необходимости можно зафиксировать порт через upload_port / monitor_port.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

upload_port = COM4
monitor_port = COM4

lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
